{% set name = "dtumathtools" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ad4b6068400d37503956ade3ecdbb264c4a0302e8a5795e62ebee8ad7a93bdb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.13
    - pip
    - setuptools_scm
    - pyproject-metadata
  run:
    - python >=3.7,<3.13
    - sympy ~=1.12
    - matplotlib ==3.6.*
    - jupyter >=1.0.0
    - numpy >=1.24
    - sympy_plot_backends >=2.4,<3

  run_constrained:
    # define optional dependencies and how they should be
    # versioned.
    # k3d
    - vtk
    - k3d >=2.9.7

    - ipympl >=0.7.0

    - plotly >=4.14.3

    # bokeh
    - panel >=1.0.0
    - ipywidgets_bokeh
    - colorcet

    # QT
    - pyqt ~=5.15.9

    # myavi (also depends on vtk)
    - ipyevents
    - mayavi ~=4.8,>=4.8.2

test:
  imports:
    - dtumathtools
  requires:
    - pip
    - pytest
    - vtk
    - k3d
    - ipympl
    - plotly
    - panel
    - ipywidgets-bokeh
    - colorcet
    - pyqt
    - ipyevents
    # currently we need 4.8.2 to be released... so it won't work... :(
    #- mayavi
  source_files:
    - tests
  commands:
    - pip check
    # we won't test the plots (for now)
    # The problem is that they require mayavi which is not installed here.. :(
    # And currently we don't want to pip install that package (might do it later)
    - pytest tests -k "not test_boundary and not test_quiver and not test_scatterplot"

about:
  home: https://github.com/dtudk/dtumathtools
  summary: 'A plotting package for the Mathematics 1 course at the Technical University of Denmark'
  description: 'A plotting package for the Mathematics 1 course at the Technical University of Denmark'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/dtudk/dtumathtools
  dev_url: https://github.com/dtudk/dtumathtools

extra:
  recipe-maintainers:
    - nicpa-dtu
    - zerothi
    - Chrillebon
