schema_version: 1

context:
  name: dtumathtools
  version: "2025.2.0"
  python_min: "3.10"
  python_max: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4f6d66d1578b44b9bf20da276cb8b05dc09cc04ebb6c0669eee0e8837f207fd7

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools_scm >=6.2
    - pyproject-metadata
  run:
    - python >=${{ python_min }},<=${{ python_max }}
    - sympy ~=1.12
    - matplotlib >=3.8,<3.10
    - jupyter >=1.0.0
    - numpy >=1.24,<2
    - sympy_plot_backends >=3.4,<4
  run_constraints:
    - vtk
    - k3d >=2.9.7
    - ipympl >=0.7.0
    - plotly >=4.14.3
    - panel >=1.0.0
    - ipywidgets_bokeh
    - colorcet
    - pyqt ~=5.15.9
    - ipyevents
    - mayavi ~=4.8,>=4.8.2

tests:
  - python:
      python_version:
        - "${{ python_min }}"
        - "${{ python_max }}"
      imports:
        - dtumathtools
      pip_check: true
  - requirements:
      run:
        # Our most important things is to test
        # against a newer python version (than the 3.9).
        # Hence we test on a more recent python version.
        # It is not ideal, but good enough.
        - pip
        - pytest
        - vtk
        - k3d
        - ipympl
        - plotly
        - panel
        - ipywidgets-bokeh
        - colorcet
        - pyqt
        - ipyevents
        - deepcomparer
    files:
      source:
        - tests
    script:
      - pytest tests -k "not test_boundary and not test_quiver and not test_scatterplot"

about:
  summary: A plotting package for the Mathematics 1a/1b course at the Technical University of Denmark
  description: A plotting package for the Mathematics 1a/1b course at the Technical University of Denmark
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/dtudk/dtumathtools
  repository: https://github.com/dtudk/dtumathtools
  documentation: https://github.com/dtudk/dtumathtools

extra:
  recipe-maintainers:
    - nicpa-dtu
    - zerothi
    - Chrillebon
